Replace AT 14.0 symlinks with files
Prepare for removal of older AT configuration.

Signed-off-by: Erwan Prioul <erwan@linux.ibm.com>

diff --git a/configs/14.0/deb/monolithic/runtime.postinst b/configs/14.0/deb/monolithic/runtime.postinst
--- a/configs/14.0/deb/monolithic/runtime.postinst
+++ b/configs/14.0/deb/monolithic/runtime.postinst
@@ -1,1 +1,37 @@
-../../../13.0/deb/monolithic/runtime.postinst
+#!/bin/bash
+#
+# Copyright 2021 IBM Corporation
+#
+# Licensed under the Apache License, Version 2.0 (the "License");
+# you may not use this file except in compliance with the License.
+# You may obtain a copy of the License at
+#
+#    http://www.apache.org/licenses/LICENSE-2.0
+#
+# Unless required by applicable law or agreed to in writing, software
+# distributed under the License is distributed on an "AS IS" BASIS,
+# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+# See the License for the specific language governing permissions and
+# limitations under the License.
+#
+
+if [[ "${1}" == configure ]]; then
+	# Automatically set the timezone
+	rm -f "__AT_DEST__/etc/localtime"
+	ln -s /etc/localtime "__AT_DEST__/etc/localtime"
+
+	# Update ld.so.cache
+	[[ -f __AT_DEST__/sbin/ldconfig ]] && __AT_DEST__/sbin/ldconfig
+fi
+
+if [[ "__USE_SYSTEMD__" == "yes" && -n "$(command -v systemctl)"\
+	&& "$(systemctl is-system-running)" != "offline" ]]; then
+	systemctl --no-reload preset __AT_VER_ALTERNATIVE__-cachemanager.service \
+	    > /dev/null 2>&1 || :
+	systemctl restart __AT_VER_ALTERNATIVE__-cachemanager.service || \
+	    echo -e " Failed to start __AT_VER_ALTERNATIVE__-cachemanager.service.\n \
+AT's linker cache file is not automatically updated when a package is \
+installed or modified.\n \
+Please run __AT_DEST__/bin/watch_ldconfig if you want it to be."
+
+fi
