Update tbb on AT next
Bump to version 2021.4.0
Bump to revision df3096075a00

Signed-off-by: Erwan Prioul <erwan@linux.ibm.com>
Signed-off-by: Cherbot <tcbot@linux.ibm.com>

diff --git a/configs/next/packages/tbb/sources b/configs/next/packages/tbb/sources
--- a/configs/next/packages/tbb/sources
+++ b/configs/next/packages/tbb/sources
@@ -1,1 +1,103 @@
-../../../15.0/packages/tbb/sources
+#!/usr/bin/env bash
+#
+# Copyright 2021 IBM Corporation
+#
+# Licensed under the Apache License, Version 2.0 (the "License");
+# you may not use this file except in compliance with the License.
+# You may obtain a copy of the License at
+#
+#    http://www.apache.org/licenses/LICENSE-2.0
+#
+# Unless required by applicable law or agreed to in writing, software
+# distributed under the License is distributed on an "AS IS" BASIS,
+# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+# See the License for the specific language governing permissions and
+# limitations under the License.
+#
+
+# TBB source package and build info
+# =======================================
+#
+
+ATSRC_PACKAGE_NAME="Thread Building Blocks"
+ATSRC_PACKAGE_VER=2021.4.0
+ATSRC_PACKAGE_REV=df3096075a00
+ATSRC_PACKAGE_BRANCH=onetbb_2021
+ATSRC_PACKAGE_LICENSE="GPL 2.0"
+ATSRC_PACKAGE_DOCLINK="https://www.threadingbuildingblocks.org/"
+ATSRC_PACKAGE_RELFIXES=
+ATSRC_PACKAGE_STR_VER="${ATSRC_PACKAGE_NAME} ${ATSRC_PACKAGE_VER}-${ATSRC_PACKAGE_REV}"
+ATSRC_PACKAGE_VERID="${ATSRC_PACKAGE_VER}${ATSRC_PACKAGE_REV:+-${ATSRC_PACKAGE_REV}}"
+ATSRC_PACKAGE_PRE="test -d tbb-${ATSRC_PACKAGE_VER}-${ATSRC_PACKAGE_REV}"
+ATSRC_PACKAGE_CO=([0]="git clone https://github.com/01org/tbb.git tbb")
+ATSRC_PACKAGE_GIT="git checkout -b tbb-${ATSRC_PACKAGE_VER}-${ATSRC_PACKAGE_REV} ${ATSRC_PACKAGE_REV}"
+ATSRC_PACKAGE_POST="mv tbb tbb-${ATSRC_PACKAGE_VER}-${ATSRC_PACKAGE_REV}"
+ATSRC_PACKAGE_SRC=${AT_BASE}/sources/tbb-${ATSRC_PACKAGE_VER}-${ATSRC_PACKAGE_REV}
+ATSRC_PACKAGE_WORK=${AT_WORK_PATH}/tbb
+ATSRC_PACKAGE_MLS=""
+ATSRC_PACKAGE_ALOC=""
+ATSRC_PACKAGE_PATCHES=""
+ATSRC_PACKAGE_TARS=""
+# Disable make check testing due to failures
+ATSRC_PACKAGE_MAKE_CHECK=none
+ATSRC_PACKAGE_DISTRIB=yes
+ATSRC_PACKAGE_BUNDLE=mcore-libs
+ATSRC_PACKAGE_UPSTREAM='wget -qO - "https://raw.githubusercontent.com/01org/tbb/__REVISION__/include/oneapi/tbb/version.h" | grep " TBB_VERSION_[MP][AI]" | sort | sed "s/[^0-9]*//g" | tr "\n" "." | cut -d. -f1-3'
+
+# This is a package function to verify the make_check log.
+# In some cases 'make check' will return 0 even though the log shows that
+# there some failures did occur.  Define this function for
+# packages where that has happened.  Due to differences in the implementations
+# of 'make check' or 'make test' the strings that indicate failure could
+# be different.
+
+atsrc_package_verify_make_check_log ()
+{
+	if [[ -n "${1}" ]]; then
+		grep -i "error[: ]" "${1}" > /dev/null
+		return ${?}
+	fi
+}
+
+atsrc_get_patches ()
+{
+	# Remove arch macros, commit from the master branch
+	at_get_patch \
+		'https://github.com/oneapi-src/oneTBB/commit/fa944e19600500863507ed8e9b1f5a30037d9df6.patch' \
+		b4c510226c8d79d524166041c6750747 || return ${?}
+	# Remove some gcc 11 warnings, commits from the master branch
+	at_get_patch \
+		'https://github.com/oneapi-src/oneTBB/commit/81dd27c4f699d4c1a8f368b1f46bffc37a864da0.patch' \
+		1f3eea49cfbdcde34efca34234232bd4 || return ${?}
+	at_get_patch \
+		'https://github.com/oneapi-src/oneTBB/commit/ec505c7d5af7b3776b6732a8351107926b7b6461.patch' \
+		1fc2a4a34e8f38f53d19d5897a81a284 || return ${?}
+	at_get_patch \
+		'https://github.com/oneapi-src/oneTBB/commit/5a643c2360fb7684b6a88eccf4421f8c635668f5.patch' \
+		d9317888c2b46ce9000658ffd7cc7db2 || return ${?}
+	# Fix size of array, part of commit from the master branch
+        at_get_patch \
+		'https://raw.githubusercontent.com/powertechpreview/powertechpreview/2da51fd320781ee9f5dd353b681258f13b04d66b/TBB%20PowerPC%20Patches/2021.3/tbb_fix_array_size.patch' \
+		baed2e1078e200d0314947ef8911c78a || return ${?}
+
+	return 0
+}
+
+atsrc_apply_patches ()
+{
+	patch -p1 \
+	     < fa944e19600500863507ed8e9b1f5a30037d9df6.patch \
+		|| return ${?}
+	patch -p1 \
+	     < 81dd27c4f699d4c1a8f368b1f46bffc37a864da0.patch \
+		|| return ${?}
+	patch -p1 \
+	     < ec505c7d5af7b3776b6732a8351107926b7b6461.patch \
+		|| return ${?}
+	patch -p1 \
+	     < 5a643c2360fb7684b6a88eccf4421f8c635668f5.patch \
+		|| return ${?}
+	patch -p1 \
+	     < tbb_fix_array_size.patch \
+		|| return ${?}
+}
